Assignment2/urls.py
from django.contrib import admin
from django.urls import path, include
from main.views import show_main, create_product, show_xml, show_json, show_xml_by_id, show_json_by_id

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'),
    path('auth/', include('authentication.urls')),
]

main/urls.py
from django.urls import path
from main.views import create_product_flutter, show_main, create_product,show_xml,show_json,show_xml_by_id,show_json_by_id, register, login_user, logout_user, delete_item, increment_item, decrement_item, edit_item,get_product_json, add_product_ajax, delete_item_ajax

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('create-product', create_product, name='create_product'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('delete/<int:id>', delete_item, name='delete_item'),
    path('increment/<int:id>', increment_item, name='increment_item'),
    path('decrement/<int:id>', decrement_item, name='decrement_item'),
    path('edit/<int:id>', edit_item, name='edit_item'),
    path('get-product/', get_product_json, name='get_product_json'),
    path('create-product-ajax/', add_product_ajax, name='add_product_ajax'),
    path('delete/ajax/', delete_item_ajax, name='delete_item_ajax'),
    path('create-flutter/', create_product_flutter, name='create_product_flutter'),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User

class Item(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    amount = models.IntegerField()
    price = models.DecimalField(max_digits=19, decimal_places=2)
    category = models.CharField(max_length=255)
    description = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

main/forms.py
from django.forms import ModelForm
from main.models import Item
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class ItemForm(ModelForm):
    class Meta:
        model = Item
        fields = [
            "name",
            "amount",
            "price",
            "category",
            "description",
            ]
        
class LoginForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "Username",
                "class": "form-control"
            }
        ))
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Password",
                "class": "form-control"
            }
        ))
    
class SignUpForm(UserCreationForm):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "Username",
                "class": "form-control"
            }
        ))
    password1 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Password",
                "class": "form-control"
            }
        ))
    password2 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Password check",
                "class": "form-control"
            }
        ))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

main/views.py
import json
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponseNotFound,JsonResponse
from main.models import Item
from main.forms import ItemForm, LoginForm, SignUpForm
from django.http import HttpResponse
from django.core import serializers
from django.urls import reverse
from django.http import HttpResponse
from django.core import serializers
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
import datetime
from django.views.decorators.csrf import csrf_exempt


@login_required(login_url='/login')
def show_main(request):

    dataAll = Item.objects.filter(user=request.user)
    dataCount = dataAll.count()
    
    context = {
        'appname': 'Adam Inventory',
        'name': 'Adam Muhammad',
        'class': 'KKI',
        'datas': dataAll,
        'dataCounts' : dataCount,
        'last_login': datetime.datetime.strptime(request.COOKIES['last_login'], '%Y-%m-%d %H:%M:%S.%f'),
    }

    return render(request, 'main.html', context)

@login_required(login_url='/login')
def create_product(request):
    form = ItemForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        product = form.save(commit=False)
        product.user = request.user
        product.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {
        'form': form,
         'last_login': datetime.datetime.strptime(request.COOKIES['last_login'], '%Y-%m-%d %H:%M:%S.%f'),
         }
    return render(request, "create_product.html", context)

@login_required(login_url='/login')
def show_xml(request):
    data = Item.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = Item.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

@login_required(login_url='/login')
def show_xml_by_id(request, id):
    data = Item.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

@login_required(login_url='/login')
def show_json_by_id(request, id):
    data = Item.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")


def register(request):
    form = UserCreationForm()
    msg = None
    # success = False

    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get("username")
            raw_password = form.cleaned_data.get("password1")
            user = authenticate(username=username, password=raw_password)

            msg = 'User created - please <a href="/login">login</a>.'
            success = True

        else:
            msg = 'Form is not valid'
    else:
        form = SignUpForm()
    context = {"form": form, "msg": msg}
    return render(request, "register.html", context)

def login_user(request):

    form = LoginForm(request.POST or None)

    msg = None
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("main:show_main"))
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            msg = messages.info(request, 'Sorry, incorrect username or password. Please try again.')
    context = {"form": form, "msg": msg}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

@login_required(login_url='/login')
def delete_item(request, id):
    try:
        data = Item.objects.get(id=id)
        data.delete()
        return HttpResponseRedirect(reverse('main:show_main'))
    except Item.DoesNotExist:
        return HttpResponse(status=204)
    
@login_required(login_url='/login')
def delete_item_ajax(request, id):
    try:
        data = Item.objects.get(id=id)
        data.delete()
        return HttpResponse(b"OK", status=201)
    except Item.DoesNotExist:
        return HttpResponse(status=204)

@login_required(login_url='/login')
def increment_item(request, id):
    data = Item.objects.get(id=id)
    data.amount += 1
    data.save()

    return HttpResponseRedirect(reverse('main:show_main'))

@login_required(login_url='/login')
def decrement_item(request, id):
    data = Item.objects.get(id=id)
    data.amount -= 1

    if data.amount == 0:
        data.delete()
        return HttpResponseRedirect(reverse('main:show_main'))
    else:
        data.save()
        return HttpResponseRedirect(reverse('main:show_main'))

@login_required(login_url='/login')
def edit_item(request, id):
    data = Item.objects.get(pk=id)
    form = ItemForm(request.POST or None, instance=data)

    if form.is_valid() and request.method == "POST":
        form.save()
        return HttpResponseRedirect(reverse('main:show_main'))
    
    context = {'form': form, 'last_login': datetime.datetime.strptime(request.COOKIES['last_login'], '%Y-%m-%d %H:%M:%S.%f'),}
    return render(request, "edit.html", context)
    

def get_product_json(request):
    product_item = Item.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize('json', product_item))

@csrf_exempt
def add_product_ajax(request):
    if request.method == 'POST':
        name = request.POST.get("name")
        amount = request.POST.get("amount")
        price = request.POST.get("price")
        category = request.POST.get("category")
        description = request.POST.get("description")
        user = request.user

        new_product = Item(name=name, amount=amount, category=category,price=price, description=description, user=user)
        new_product.save()

        return HttpResponse(b"CREATED", status=201)

    return HttpResponseNotFound()

@csrf_exempt
def create_product_flutter(request):
    if request.method == 'POST':
        
        data = json.loads(request.body)

        new_product = Item.objects.create(
            user = request.user,
            name = data["name"],
            amount = int(data["amount"]),
            price = int(data["price"]),
            category = data["category"],
            description = data["description"]
        )

        new_product.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

main/templates/create_product.html
{% extends 'base.html' %}

{% block content %}

<form method="POST">
    {% csrf_token %}
    <div class="col-md-12">
        <div class="card ">
            <div class="card-header card-header-rose card-header-text">
                <div class="card-text">
                    <h4 class="card-title">Add New Item</h4>
                </div>
            </div>
            <div class="card-body ">
                <form method="get" action="/" class="form-horizontal">
                    <div class="row">
                        <label class="col-sm-2 col-form-label">Item Name</label>
                        <div class="col-sm-10">
                            <div class="form-group">
                                <input type="text" name="name" class="form-control" placeholder="Item Name">
                                <span class="bmd-help">Name of the item</span>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <label class="col-sm-2 col-form-label">Amount</label>
                        <div class="col-sm-10">
                            <div class="form-group">
                                <input type="number" name="amount" class="form-control" placeholder="Amount">
                                <span class="bmd-help">Amount of the item</span>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <label class="col-sm-2 col-form-label">Price</label>
                        <div class="col-sm-10">
                            <div class="form-group">
                                <input type="number" name="price" class="form-control" placeholder="Price">
                                <span class="bmd-help">Price of the item</span>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <label class="col-sm-2 col-form-label">Category</label>
                        <div class="col-sm-10">
                            <div class="form-group">
                                <input type="text" name="category" class="form-control" placeholder="Item Category">
                                <span class="bmd-help">Category of the item</span>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <label class="col-sm-2 col-form-label">Description</label>
                        <div class="col-sm-10">
                            <div class="form-group">
                                <input type="text" name="description" class="form-control" placeholder="Description">
                                <span class="bmd-help">Description of the item</span>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <div class="card-footer ml-auto mr-auto">
                <button type="submit" class="btn btn-rose" value="add item">Add</button>
            </div>
        </div>
    </div>
</form>

{% endblock %}

main/templates/edit.html
{% extends 'base.html' %}

{% block content %}

<form method="POST">
    {% csrf_token %}
    <div class="col-md-12">
        <div class="card ">
            <div class="card-header card-header-rose card-header-text">
                <div class="card-text">
                    <h4 class="card-title">Edit Item</h4>
                </div>
            </div>
            <div class="card-body ">
                <form method="post" action="/" class="form-horizontal">
                    <div class="row">
                        <label class="col-sm-2 col-form-label">Item Name</label>
                        <div class="col-sm-10">
                            <div class="form-group">
                                <input type="text" name="name" value="{{form.instance.name}}" class="form-control"
                                    placeholder="Item Name">
                                <span class="bmd-help">Name of the item</span>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <label class="col-sm-2 col-form-label">Amount</label>
                        <div class="col-sm-10">
                            <div class="form-group">
                                <input type="number" name="amount" value="{{form.instance.amount}}" class="form-control"
                                    placeholder="Amount">
                                <span class="bmd-help">Amount of the item</span>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <label class="col-sm-2 col-form-label">Price</label>
                        <div class="col-sm-10">
                            <div class="form-group">
                                <input type="number" name="price" value="{{form.instance.price}}" class="form-control"
                                    placeholder="Price">
                                <span class="bmd-help">Price of the item</span>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <label class="col-sm-2 col-form-label">Category</label>
                        <div class="col-sm-10">
                            <div class="form-group">
                                <input type="text" name="category" value="{{form.instance.category}}"
                                    class="form-control" placeholder="Item Category">
                                <span class="bmd-help">Category of the item</span>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <label class="col-sm-2 col-form-label">Description</label>
                        <div class="col-sm-10">
                            <div class="form-group">
                                <input type="text" name="description" value="{{form.instance.description}}"
                                    class="form-control" placeholder="Description">
                                <span class="bmd-help">Description of the item</span>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <div class="card-footer ml-auto mr-auto">
                <button type="submit" class="btn btn-rose" value="edit item">Edit</button>
            </div>
        </div>
    </div>
</form>

{% endblock %}

main/templates/login.html
{% extends "base-auth.html" %}

{% block title %} Login {% endblock title %}

{% block content %}

<div class="page-header login-page header-filter" filter-color="black"
    style="background-image: url('/main/static/assets/img/login.jpg'); background-size: cover; background-position: top center;">
    <div class="container">
        <div class="row">
            <div class="col-lg-4 col-md-6 col-sm-8 ml-auto mr-auto">

                <form role="form" method="post" action="">

                    {% csrf_token %}

                    <div class="card card-login card-hidden">
                        <div class="card-header card-header-rose text-center">
                            <h4 class="card-title">
                                Login Inventory
                            </h4>
                        </div>
                        <div class="card-body ">
                            <p class="card-description text-center">

                                {% if msg %}
                                {{ msg | safe }}
                                {% else %}
                                <span>
                                    Add your credentials
                                </span>
                                {% endif %}

                            </p>

                            <span class="bmd-form-group">
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text">
                                            <i class="material-icons">face</i>
                                        </span>
                                    </div>
                                    {{ form.username }}
                                </div>
                            </span>

                            <span class="bmd-form-group">
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text">
                                            <i class="material-icons">lock_outline</i>
                                        </span>
                                    </div>
                                    {{ form.password }}
                                </div>
                            </span>


                        </div>
                        <div class="card-footer justify-content-center">
                            <button type="submit" name="login" class="btn btn-primary my-4">Login</button>
                        </div>

                        <br />

                    </div>
                </form>

            </div>
        </div>
    </div>

    {% include 'footer.html' %}

</div>

{% endblock content %}

{% block javascripts %}

<script>
    $(document).ready(function () {
        md.checkFullPageBackgroundImage();
        setTimeout(function () {
            $('.card').removeClass('card-hidden');
        }, 700);
    });
</script>

{% endblock javascripts %}

main/templates/main.html
{% extends "base.html" %}

{% block title %} Datatables {% endblock title %}

{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header card-header-primary card-header-icon">
                <h4 class="card-title">List of Inventory Items</h4>
                <!-- <button type="button" class="btn btn-success btn-sm float-right" data-toggle="modal"
                    data-target="#addDataModal">
                    Add Item
                </button> -->
            </div>
            <div class="card-body">
                <div class="toolbar">
                </div>
                <div class="material-datatables">
                    <table id="datatables" class="table table-striped table-no-bordered table-hover" cellspacing="0"
                        width="100%" style="width:100%">
                    </table>
                    <br />
                    <p id="totalItem"></p>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="addDataModal" tabindex="-1" role="dialog" aria-labelledby="addDataModalLabel"
    aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="modalAddItem">Add New Product</h1>
                <button type="button" class="btn-close" data-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="form" onsubmit="return false;">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="name" class="col-form-label">Name:</label>
                        <input type="text" class="form-control" id="name" name="name"></input>
                    </div>
                    <div class="mb-3">
                        <label for="amount" class="col-form-label">Amount:</label>
                        <input type="number" class="form-control" id="amount" name="amount"></input>
                    </div>
                    <div class="mb-3">
                        <label for="price" class="col-form-label">Price:</label>
                        <input type="number" class="form-control" id="price" name="price"></input>
                    </div>
                    <div class="mb-3">
                        <label for="category" class="col-form-label">Category:</label>
                        <input type="text" class="form-control" id="category" name="category"></input>
                    </div>
                    <div class="mb-3">
                        <label for="description" class="col-form-label">Description:</label>
                        <textarea class="form-control" id="description" name="description"></textarea>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" id="btnAdd" data-dismiss="modal">Add
                    Product</button>

            </div>
        </div>
    </div>
</div>


{% endblock content %}

{% block javascripts %}

<script>
    $(document).ready(function () {
        $('#datatables').DataTable({
            "pagingType": "full_numbers",
            "lengthMenu": [
                [10, 25, 50, -1],
                [10, 25, 50, "All"]
            ],
            responsive: true,
            language: {
                search: "_INPUT_",
                searchPlaceholder: "Search records",
            }
        });

        var table = $('#datatable').DataTable();

        // Edit record
        table.on('click', '.edit', function () {
            $tr = $(this).closest('tr');
            var data = table.row($tr).data();
            alert('You press on Row: ' + data[0] + ' ' + data[1] + ' ' + data[2] + '\'s row.');
        });

        // Delete a record
        table.on('click', '.remove', function (e) {
            $tr = $(this).closest('tr');
            table.row($tr).remove().draw();
            e.preventDefault();
        });

        //Like record
        table.on('click', '.like', function () {
            alert('You clicked on Like button');
        });
    });
</script>

<script>
    async function getProducts() {
        return fetch("{% url 'main:get_product_json' %}").then((res) => res.json())
    }

    async function refreshProducts() {
        document.getElementById("datatables").innerHTML = ""
        const products = await getProducts()
        let htmlString = `<thead>
                            <tr>
                                <th>Name</th>
                                <th>Amount</th>
                                <th>Price</th>
                                <th>Category</th>
                                <th>Description</th>
                                <th>Date Added</th>
                                <th>Action</th>
                            </tr>
                        </thead>`
        products.forEach((item) => {
            htmlString += `\n
        
        <tbody>
                            <tr>
                                <td>${item.fields.name}</td>
                                <td>
                                    <a href="/increment/${item.pk}">
                                        <button type="button" rel="tooltip" class="btn btn-primary btn-just-icon btn-sm">
                                            <i class="material-icons">add</i>
                                        </button>
                                    </a>
                                    ${item.fields.amount}
                                    <a href="/decrement/${item.pk}">
                                        <button type="button" rel="tooltip" class="btn btn-primary btn-just-icon btn-sm"
                                        onclick="return confirm('If the amount less than 1, the data will be deleted!');">
                                            <i class="material-icons">remove</i>
                                        </button>
                                    </a>
                                </td>
                                <td>${item.fields.price}</td>
                                <td>${item.fields.category}</td>
                                <td>${item.fields.description}</td>
                                <td>${item.fields.date_added}</td>
                                <td>
                                    <a href="/edit/${item.pk}">
                                        <button type="button" rel="tooltip" class="btn btn-success btn-just-icon btn-sm"
                                            onclick="return confirm('Are you sure you want to edit this item?');">
                                            <i class="material-icons">create</i>
                                        </button>
                                    </a>
                                    
                                    <a href="/delete/${item.pk}">
                                        <button type="button" rel="tooltip" id="deleteBtn" class="btn btn-danger btn-just-icon btn-sm"
                                            onclick="return confirm('Are you sure you want to delete this item?');">
                                            <i class="material-icons">close</i>
                                        </button>
                                    </a>
                                </td>
                            </tr>
                        </tbody>`
        })

        document.getElementById("datatables").innerHTML = htmlString
        document.getElementById("totalItem").innerHTML = `You have saved ${products.length} items in this application`
    }

    refreshProducts()

    // let delete_button = document.getElementById("deleteBtn")
    //     for (var i = 0; i < delete_button.length; i++) {
    //         delete_button[i].addEventListener('click', () => {
    //             deleteProduct(event.currentTarget)
    //         })
    //     }

    function addProduct() {
        fetch("{% url 'main:add_product_ajax' %}", {
            method: "POST",
            body: new FormData(document.querySelector('#form'))
        }).then(refreshProducts)

        document.getElementById("form").reset()
        return false
    }

    function deleteProduct(button) {
        fetch("{% url 'main:delete_item_ajax' %}", {
            method: "POST",
            body: new FormData(button.closest('form'))
        }).then(fetchProducts)

        document.getElementById("form").reset()
        return false
    }
    document.getElementById("btnAdd").onclick = addProduct
    document.getElementById("deleteBtn").onclick = addProduct
</script>


{% endblock javascripts %}